=== michaelmccord/cfn-schema/schema/base.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "description": "AWS CloudFormation template. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-guide.html",
  "type": "object",
  "required": [
    "Resources"
  ],
  "properties": {
    "AWSTemplateFormatVersion": {
      "description": "The AWS CloudFormation template version that the template conforms to. The template format version is not the same as the API or WSDL version. The template format version can change independently of the API and WSDL versions. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html",
      "type": "string",
      "enum": [
        "2010-09-09"
      ]
    },
    "Description": {
      "description": "A text string that describes the template. This section must always follow the template format version section. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-description-structure.html",
      "type": "string",
      "minLength": 0,
      "maxLength": 1024
    },
    "Metadata": {
      "type": "object",
      "description": "Objects that provide additional information about the template. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/metadata-section-structure.html",
      "properties": {
        "AWS::CloudFormation::Init": {
          "type": "object",
          "description": "Defines configuration tasks for the cfn-init helper script. This script is useful for configuring and installing applications on EC2 instances. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-init.html"
        },
        "AWS::CloudFormation::Interface": {
          "type": "object",
          "description": "Defines the grouping and ordering of input parameters when they are displayed in the AWS CloudFormation console. By default, the AWS CloudFormation console alphabetically sorts parameters by their logical ID. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-interface.html"
        },
        "AWS::CloudFormation::Designer": {}
      },
      "additionalProperties": {
        "type": "object"
      }
    },
    "Parameters": {
      "type": "object",
      "description": "Values to pass to your template at runtime (when you create or update a stack). You can refer to parameters from the Resources and Outputs sections of the template. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html",
      "additionalProperties": {
        "type": "object",
        "required": [
          "Type"
        ],
        "properties": {
          "AllowedPattern": {
            "type": "string",
            "description": "A regular expression that represents the patterns to allow for String types."
          },
          "AllowedValues": {
            "type": "array",
            "description": "An array containing the list of values allowed for the parameter."
          },
          "ConstraintDescription": {
            "type": "string",
            "description": "A string that explains a constraint when the constraint is violated."
          },
          "Default": {
            "type": "string",
            "description": "A value of the appropriate type for the template to use if no value is specified when a stack is created. If you define constraints for the parameter, you must specify a value that adheres to those constraints."
          },
          "Description": {
            "type": "string",
            "description": "A string of up to 4000 characters that describes the parameter.",
            "minLength": 0,
            "maxLength": 4000
          },
          "MaxLength": {
            "type": "integer",
            "description": "An integer value that determines the largest number of characters you want to allow for String types."
          },
          "MaxValue": {
            "type": "number",
            "description": "A numeric value that determines the largest numeric value you want to allow for Number types."
          },
          "MinLength": {
            "type": "integer",
            "description": "An integer value that determines the smallest number of characters you want to allow for String types."
          },
          "MinValue": {
            "type": "number",
            "description": "A numeric value that determines the smallest numeric value you want to allow for Number types."
          },
          "NoEcho": {
            "type": "boolean",
            "description": "Whether to mask the parameter value when anyone makes a call that describes the stack. If you set the value to true, the parameter value is masked with asterisks (*****)."
          },
          "Type": {
            "type": "string",
            "description": "The data type for the parameter (DataType).",
            "enum": [
              "String",
              "Number",
              "List<Number>",
              "CommaDelimitedList",
              "AWS::EC2::AvailabilityZone::Name",
              "AWS::EC2::Image::Id",
              "AWS::EC2::Instance::Id",
              "AWS::EC2::KeyPair::KeyName",
              "AWS::EC2::SecurityGroup::GroupName",
              "AWS::EC2::SecurityGroup::Id",
              "AWS::EC2::Subnet::Id",
              "AWS::EC2::Volume::Id",
              "AWS::EC2::VPC::Id",
              "AWS::Route53::HostedZone::Id",
              "List<AWS::EC2::AvailabilityZone::Name>",
              "List<AWS::EC2::Image::Id>",
              "List<AWS::EC2::Instance::Id>",
              "List<AWS::EC2::SecurityGroup::GroupName>",
              "List<AWS::EC2::SecurityGroup::Id>",
              "List<AWS::EC2::Subnet::Id>",
              "List<AWS::EC2::Volume::Id>",
              "List<AWS::EC2::VPC::Id>",
              "List<AWS::Route53::HostedZone::Id>"
            ]
          }
        }
      }
    },
    "Mappings": {
      "type": "object",
      "description": "A mapping of keys and associated values that you can use to specify conditional parameter values, similar to a lookup table. You can match a key to a corresponding value by using the Fn::FindInMap intrinsic function in the Resources and Outputs section. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html",
      "additionalProperties": {
        "type": "object",
        "additionalProperties": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        }
      }
    },
    "Conditions": {
      "type": "object",
      "description": "Conditions that control whether certain resources are created or whether certain resource properties are assigned a value during stack creation or update. For example, you could conditionally create a resource that depends on whether the stack is for a production or test environment. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html"
    },
    "Transform": {
      "description": "For serverless applications (also referred to as Lambda-based applications), specifies the version of the AWS Serverless Application Model (AWS SAM) to use. When you specify a transform, you can use AWS SAM syntax to declare resources in your template. The model defines the syntax that you can use and how it is processed. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html"
    },
    "Resources": {
      "type": "object",
      "description": "Specifies the stack resources and their properties, such as an Amazon Elastic Compute Cloud instance or an Amazon Simple Storage Service bucket. You can refer to resources in the Resources and Outputs sections of the template. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html"
    },
    "Outputs": {
      "type": "object",
      "description": "Describes the values that are returned whenever you view your stack's properties. For example, you can declare an output for an S3 bucket name and then call the aws cloudformation describe-stacks AWS CLI command to view the name. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html"
    }
  }
}

=== michaelmccord/cfn-schema/template.cfn.json
{
  "Transform": "AWS::Serverless-2016-10-31",
  "Parameters": {
    "AcmCertificateArn": {
      "ConstraintDescription": "must be valid ARN.",
      "Default": "",
      "Description": "ARN of a Amazon Certificate Manager certificate.",
      "Type": "String"
    },
    "DistributionAliases": {
      "ConstraintDescription": "must be comma-delimited FQDNs.",
      "Default": "",
      "Description": "FQDNs as aliases to the CloudFront Distribution, comma-delimited.",
      "Type": "CommaDelimitedList"
    }
  },
  "Conditions": {
    "UseCertificateCond": {
      "Fn::Not": [
        {
          "Fn::Equals": [
            {
              "Ref": "AcmCertificateArn"
            },
            ""
          ]
        }
      ]
    },
    "UseDistributionAliasesCond": {
      "Fn::Not": [
        {
          "Fn::Equals": [
            {
              "Fn::Join": [
                ",",
                {
                  "Ref": "DistributionAliases"
                }
              ]
            },
            ""
          ]
        }
      ]
    }
  },
  "Resources": {
    "Function1": {
      "Type": "AWS::Serverless::Function",
      "Properties": {
        "Handler": "index.handler",
        "Runtime": "nodejs6.10",
        "CodeUri": "src/",
        "Events": {
          "GetResource": {
            "Type": "Api",
            "Properties": {
              "Path": "/hello",
              "Method": "get"
            }
          }
        }
      }
    },
    "Distribution": {
      "Type": "AWS::CloudFront::Distribution",
      "Properties": {
        "DistributionConfig": {
          "Enabled": true,
          "HttpVersion": "http2",
          "Comment": {
            "Ref": "AWS::StackName"
          },
          "Aliases": {
            "Fn::If": [
              "UseDistributionAliasesCond",
              {
                "Ref": "DistributionAliases"
              },
              {
                "Ref": "AWS::NoValue"
              }
            ]
          },
          "DefaultCacheBehavior": {
            "Compress": true,
            "TargetOriginId": "ApiGateway",
            "AllowedMethods": [
              "HEAD",
              "GET"
            ],
            "CachedMethods": [
              "HEAD",
              "GET"
            ],
            "ForwardedValues": {
              "QueryString": true
            },
            "ViewerProtocolPolicy": {
              "Fn::If": [
                "UseDistributionAliasesCond",
                {
                  "Fn::If": [
                    "UseCertificateCond",
                    "redirect-to-https",
                    "allow-all"
                  ]
                },
                "redirect-to-https"
              ]
            }
          },
          "Origins": [
            {
              "Id": "ApiGateway",
              "OriginPath": "/Prod",
              "CustomOriginConfig": {
                "OriginProtocolPolicy": "https-only",
                "OriginSSLProtocols": [
                  "TLSv1"
                ]
              },
              "DomainName": {
                "Fn::Join": [
                  "",
                  [
                    {
                      "Ref": "ServerlessRestApi"
                    },
                    ".execute-api.",
                    {
                      "Ref": "AWS::Region"
                    },
                    ".amazonaws.com"
                  ]
                ]
              }
            }
          ],
          "ViewerCertificate": {
            "Fn::If": [
              "UseCertificateCond",
              {
                "AcmCertificateArn": {
                  "Ref": "AcmCertificateArn"
                },
                "MinimumProtocolVersion": "TLSv1",
                "SslSupportMethod": "sni-only"
              },
              {
                "Ref": "AWS::NoValue"
              }
            ]
          }
        }
      }
    }
  }
}
